# Generated by Django 4.2.6 on 2023-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='12:00', verbose_name='время выполнения задачи'),
        ),
    ]
